create table addresse_user (
    id bigint generated by default as identity,
    cep varchar(9) not null,
    city varchar(50) not null,
    complement varchar(50) not null,
    country varchar(50) not null,
    last_update timestamp(6) with time zone,
    neighborhood varchar(50) not null,
    number integer not null check (number>=1),
    state varchar(50) not null,
    street varchar(255) not null,
    primary key (id)
);

create table user_credentials (
    id bigint generated by default as identity,
    last_update timestamp(6) with time zone,
    password varchar(255) not null,
    username varchar(50) not null,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    email varchar(100) not null,
    last_update timestamp(6) with time zone,
    name varchar(100) not null,
    profile varchar(255) not null check (profile in ('client','owner','admin')),
    user_identification varchar(14) not null,
    address_id bigint not null,
    user_credentials_id bigint not null,
    primary key (id)
);

alter table if exists user_credentials
   add constraint UK8pcilw7ay5rs8c4dtrtik21pw unique (username);

alter table if exists users
   add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);

alter table if exists users
   add constraint UK6rl7uwad2j44yoj9uptyvr95v unique (user_identification);

alter table if exists users
   add constraint UKhbvhqvjgmhd5omxyo67ynvbyp unique (address_id);

alter table if exists users
   add constraint UKgj5hyw12th3794d7t0lyn4lud unique (user_credentials_id);

alter table if exists users
   add constraint FK8q5fd63ltnhf6x6ky49vka1ch
   foreign key (address_id)
   references addresse_user;

alter table if exists users
   add constraint FKieycu0m84fc3fg0a3vbcm7477
   foreign key (user_credentials_id)
   references user_credentials;
